---
- hosts: all
  become: true
  tasks:
    - name: Start the Celery worker using tmux
      shell: |
        tmux new-session -d -s celery_worker "source venv/bin/activate && celery -A tasks worker -B --loglevel=WARNING"
      args:
        chdir: /home/ubuntu/gogobot/
